### ISSUE TITLE
报安装失败怎么解决

### ISSUE THREAD

**Issue by sanityq** [wzpan/wukong-starter#2]
INFO:root:执行命令 RUN wget http://hahack-1253537070.file.myqcloud.com/misc/snowboy.tar.bz2
/bin/sh: wget: command not found
ERROR:root:错误：命令 RUN wget http://hahack-1253537070.file.myqcloud.com/misc/snowboy.tar.bz2 执行失败！
ERROR:root:wukong-starter 安装失败！

**Comment by wzpan** [comment]
需要先安装 wget 。取决于你的系统。

如果是 ubuntu：

``` sh
sudo apt-get install wget
```

如果是 mac：

```
brew install wget
```

**Comment by sanityq** [comment]
x snowboy/swig/Android/Makefile
x snowboy/swig/Android/install_ndk.sh
x snowboy/swig/Java/snowboy-detect-swig.i
x snowboy/swig/Java/Makefile
x snowboy/swig/Perl/Makefile
x snowboy/swig/Perl/snowboy-detect.i
x snowboy/swig/Python/snowboy-detect-swig.i
x snowboy/swig/Python/snowboy-detect-swig.o
x snowboy/swig/Python/snowboy-detect-swig.cc
x snowboy/swig/Python/Makefile
x snowboy/swig/Python/_snowboydetect.so
x snowboy/swig/Python/snowboydetect.py
x snowboy/swig/Python3/snowboy-detect-swig.i
x snowboy/swig/Python3/._.DS_Store
x snowboy/swig/Python3/.DS_Store
x snowboy/swig/Python3/Makefile
x snowboy/swig/Go/snowboy.go
x snowboy/swig/Go/snowboydetect.swigcxx
INFO:root:执行命令 WORKDIR $PWD/temp/snowboy/swig/Python3
INFO:root:执行命令 RUN make
/bin/sh: swig: command not found
expr: syntax error
swig -I../../ -c++ -python -o snowboy-detect-swig.cc snowboy-detect-swig.i
make: swig: No such file or directory
make: *** [snowboy-detect-swig.cc] Error 1
ERROR:root:错误：命令 RUN make 执行失败！
ERROR:root:wukong-starter 安装失败！
(base) qiqideMacBook-Pro:wukong-starter vn$ 

还是安装失败

> 在 2019年5月26日，下午11:31，潘伟洲 <notifications@github.com> 写道：
> 
> brew install wget

**Comment by wzpan** [comment]
https://wukong.hahack.com/#/install?id=%E5%AE%89%E8%A3%85-swig
参见这里，手动安装下 swig 。

**Comment by wzpan** [comment]
久无回复，先关闭了。如有问题可以重新打开。

**Comment by X-xinz** [comment]
INFO:root:缓存命令 RUN sudo apt-get install -y alsa-base pulseaudio libsox-fmt-all
INFO:root:缓存命令 RUN sudo apt-get install -y libpcre3 libpcre3-dev
INFO:root:缓存命令 RUN ./configure --prefix=/usr --without-clisp --without-maximum-compile-warnings
INFO:root:缓存命令 RUN sudo make && sudo make install
INFO:root:缓存命令 RUN sudo install -v -m755 -d /usr/share/doc/swig-3.0.10
INFO:root:缓存命令 RUN sudo cp -v -R Doc/* /usr/share/doc/swig-3.0.10
INFO:root:缓存命令 RUN sudo apt-get install -y libatlas-base-dev
INFO:root:缓存命令 RUN wget http://hahack-1253537070.file.myqcloud.com/misc/snowboy.tar.bz2
INFO:root:缓存命令 RUN tar -xvjf snowboy.tar.bz2
INFO:root:执行命令 RUN make
g++ -I../../ -O3 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++0x  -shared snowboy-detect-swig.o \
../..//lib/ubuntu64/libsnowboy-detect.a -L/usr/local/lib/python3.7/config-3.7m-x86_64-linux-gnu -L/usr/local/lib -lpython3.7m -lpthread -ldl  -lutil -lm  -Xlinker -export-dynamic -lm -ldl -lf77blas -lcblas -llapack -latlas -o _snowboydetect.so
/usr/bin/ld: /usr/local/lib/python3.7/config-3.7m-x86_64-linux-gnu/libpython3.7m.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/python3.7/config-3.7m-x86_64-linux-gnu/libpython3.7m.a: 无法添加符号: 错误的值
collect2: error: ld returned 1 exit status
Makefile:73: recipe for target '_snowboydetect.so' failed
make: *** [_snowboydetect.so] Error 1
ERROR:root:错误：命令 RUN make 执行失败！
ERROR:root:wukong-starter 安装失败！

请问这是什么情况呀

**Comment by wzpan** [comment]
@assassin0yxz 什么操作系统？

**Comment by X-xinz** [comment]
ubuntu 16.04（virtualBox）

**Comment by wzpan** [comment]
是在普通电脑上用virtualBox装的吗？按道理不会有错误才对啊……

**Comment by assassin0yxz** [comment]
是的，就是有这个问题，我重新安装ubuntu后再尝试就就没问题了，我很迷

之后就是这个
(env) yxz@yxz-VirtualBox:~/文档/wukong-starter$ pip3 install pyaudio
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting pyaudio
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ab/42/b4f04721c5c5bfc196ce156b3c768998ef8c0ae3654ed29ea5020c749a6b/PyAudio-0.2.11.tar.gz (37 kB)
Building wheels for collected packages: pyaudio
  Building wheel for pyaudio (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: '/home/yxz/文档/wukong-starter/env/bin/python' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rm2kylm9/pyaudio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rm2kylm9/pyaudio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-g1bfm092
       cwd: /tmp/pip-install-rm2kylm9/pyaudio/
  Complete output (14 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  copying src/pyaudio.py -> build/lib.linux-x86_64-3.5
  running build_ext
  building '_portaudio' extension
  creating build/temp.linux-x86_64-3.5
  creating build/temp.linux-x86_64-3.5/src
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/yxz/文档/wukong-starter/env/include -I/usr/include/python3.5m -c src/_portaudiomodule.c -o build/temp.linux-x86_64-3.5/src/_portaudiomodule.o
  src/_portaudiomodule.c:29:23: fatal error: portaudio.h: 没有那个文件或目录
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pyaudio
  Running setup.py clean for pyaudio
Failed to build pyaudio
Installing collected packages: pyaudio
    Running setup.py install for pyaudio ... error
    ERROR: Command errored out with exit status 1:
     command: '/home/yxz/文档/wukong-starter/env/bin/python' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rm2kylm9/pyaudio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rm2kylm9/pyaudio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-r2j2a2x7/install-record.txt --single-version-externally-managed --compile --install-headers '/home/yxz/文档/wukong-starter/env/include/site/python3.5/pyaudio'
         cwd: /tmp/pip-install-rm2kylm9/pyaudio/
    Complete output (14 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    copying src/pyaudio.py -> build/lib.linux-x86_64-3.5
    running build_ext
    building '_portaudio' extension
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/yxz/文档/wukong-starter/env/include -I/usr/include/python3.5m -c src/_portaudiomodule.c -o build/temp.linux-x86_64-3.5/src/_portaudiomodule.o
    src/_portaudiomodule.c:29:23: fatal error: portaudio.h: 没有那个文件或目录
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: '/home/yxz/文档/wukong-starter/env/bin/python' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rm2kylm9/pyaudio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rm2kylm9/pyaudio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-r2j2a2x7/install-record.txt --single-version-externally-managed --compile --install-headers '/home/yxz/文档/wukong-starter/env/include/site/python3.5/pyaudio' Check the logs for full command output.

**Comment by X-xinz** [comment]
是的，就是有这个问题，我重新安装ubuntu后再尝试就就没问题了，我很迷

之后就是这个
(env) yxz@yxz-VirtualBox:~/文档/wukong-starter$ pip3 install pyaudio
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting pyaudio
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ab/42/b4f04721c5c5bfc196ce156b3c768998ef8c0ae3654ed29ea5020c749a6b/PyAudio-0.2.11.tar.gz (37 kB)
Building wheels for collected packages: pyaudio
  Building wheel for pyaudio (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: '/home/yxz/文档/wukong-starter/env/bin/python' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rm2kylm9/pyaudio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rm2kylm9/pyaudio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-g1bfm092
       cwd: /tmp/pip-install-rm2kylm9/pyaudio/
  Complete output (14 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  copying src/pyaudio.py -> build/lib.linux-x86_64-3.5
  running build_ext
  building '_portaudio' extension
  creating build/temp.linux-x86_64-3.5
  creating build/temp.linux-x86_64-3.5/src
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/yxz/文档/wukong-starter/env/include -I/usr/include/python3.5m -c src/_portaudiomodule.c -o build/temp.linux-x86_64-3.5/src/_portaudiomodule.o
  src/_portaudiomodule.c:29:23: fatal error: portaudio.h: 没有那个文件或目录
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pyaudio
  Running setup.py clean for pyaudio
Failed to build pyaudio
Installing collected packages: pyaudio
    Running setup.py install for pyaudio ... error
    ERROR: Command errored out with exit status 1:
     command: '/home/yxz/文档/wukong-starter/env/bin/python' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rm2kylm9/pyaudio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rm2kylm9/pyaudio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-r2j2a2x7/install-record.txt --single-version-externally-managed --compile --install-headers '/home/yxz/文档/wukong-starter/env/include/site/python3.5/pyaudio'
         cwd: /tmp/pip-install-rm2kylm9/pyaudio/
    Complete output (14 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    copying src/pyaudio.py -> build/lib.linux-x86_64-3.5
    running build_ext
    building '_portaudio' extension
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/yxz/文档/wukong-starter/env/include -I/usr/include/python3.5m -c src/_portaudiomodule.c -o build/temp.linux-x86_64-3.5/src/_portaudiomodule.o
    src/_portaudiomodule.c:29:23: fatal error: portaudio.h: 没有那个文件或目录
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: '/home/yxz/文档/wukong-starter/env/bin/python' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rm2kylm9/pyaudio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rm2kylm9/pyaudio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-r2j2a2x7/install-record.txt --single-version-externally-managed --compile --install-headers '/home/yxz/文档/wukong-starter/env/include/site/python3.5/pyaudio' Check the logs for full command output.

**Comment by assassin0yxz** [comment]
是的，就是有这个问题，我重新安装ubuntu后再尝试就就没问题了，我很迷

之后就是这个
(env) yxz@yxz-VirtualBox:~/文档/wukong-starter$ pip3 install pyaudio
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting pyaudio
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ab/42/b4f04721c5c5bfc196ce156b3c768998ef8c0ae3654ed29ea5020c749a6b/PyAudio-0.2.11.tar.gz (37 kB)
Building wheels for collected packages: pyaudio
  Building wheel for pyaudio (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: '/home/yxz/文档/wukong-starter/env/bin/python' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rm2kylm9/pyaudio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rm2kylm9/pyaudio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-g1bfm092
       cwd: /tmp/pip-install-rm2kylm9/pyaudio/
  Complete output (14 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  copying src/pyaudio.py -> build/lib.linux-x86_64-3.5
  running build_ext
  building '_portaudio' extension
  creating build/temp.linux-x86_64-3.5
  creating build/temp.linux-x86_64-3.5/src
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/yxz/文档/wukong-starter/env/include -I/usr/include/python3.5m -c src/_portaudiomodule.c -o build/temp.linux-x86_64-3.5/src/_portaudiomodule.o
  src/_portaudiomodule.c:29:23: fatal error: portaudio.h: 没有那个文件或目录
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pyaudio
  Running setup.py clean for pyaudio
Failed to build pyaudio
Installing collected packages: pyaudio
    Running setup.py install for pyaudio ... error
    ERROR: Command errored out with exit status 1:
     command: '/home/yxz/文档/wukong-starter/env/bin/python' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rm2kylm9/pyaudio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rm2kylm9/pyaudio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-r2j2a2x7/install-record.txt --single-version-externally-managed --compile --install-headers '/home/yxz/文档/wukong-starter/env/include/site/python3.5/pyaudio'
         cwd: /tmp/pip-install-rm2kylm9/pyaudio/
    Complete output (14 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    copying src/pyaudio.py -> build/lib.linux-x86_64-3.5
    running build_ext
    building '_portaudio' extension
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/yxz/文档/wukong-starter/env/include -I/usr/include/python3.5m -c src/_portaudiomodule.c -o build/temp.linux-x86_64-3.5/src/_portaudiomodule.o
    src/_portaudiomodule.c:29:23: fatal error: portaudio.h: 没有那个文件或目录
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: '/home/yxz/文档/wukong-starter/env/bin/python' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rm2kylm9/pyaudio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rm2kylm9/pyaudio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-r2j2a2x7/install-record.txt --single-version-externally-managed --compile --install-headers '/home/yxz/文档/wukong-starter/env/include/site/python3.5/pyaudio' Check the logs for full command output.

**Comment by wzpan** [comment]
``` bash
sudo apt-get install portaudio19-dev python-all-dev python3-all-dev
pip install pyaudio
```

**Comment by X-xinz** [comment]
![0](https://user-images.githubusercontent.com/32587436/74607117-cedae500-5110-11ea-8788-231fbdc8c403.jpg)
指令发送不成功

**Comment by X-xinz** [comment]
@wzpan 请问这个是哪里的原因呢？
WARNING:tornado.general:400 POST /chat (::1): Missing argument query
WARNING:tornado.access:400 POST /chat (::1) 52.14ms

![chat](https://user-images.githubusercontent.com/32587436/74703842-82df8b80-5249-11ea-83fa-53146328e909.jpg)
![index](https://user-images.githubusercontent.com/32587436/74703858-92f76b00-5249-11ea-827e-e7f88325cc50.jpg)

**Comment by wzpan** [comment]
试试在 Chrome 的 devtool 里找到 index.js ，然后打个断点，打印出 query 的值看看有没有值。

这里有可能是你传了个空的值给了后台，比如并没有输入内容直接回车。

![image](https://user-images.githubusercontent.com/1631405/74722162-6ce6c080-5273-11ea-939b-f1e16967a399.png)

**Comment by assassin0yxz** [comment]
![Uploading 屏幕截图2.jpg…]()
![屏幕截图](https://user-images.githubusercontent.com/32587436/74727751-99eba100-527c-11ea-8db5-8952fc3e14a9.jpg)
但是这个好像是有值得呀

**Comment by X-xinz** [comment]
![1](https://user-images.githubusercontent.com/32587436/74728425-b1775980-527d-11ea-92ff-4f0dd6bdad11.jpg)
![2](https://user-images.githubusercontent.com/32587436/74728432-b3d9b380-527d-11ea-83fb-fc1703e39b30.jpg)

@wzpan 但是这个看上去应该是有值的

**Comment by X-xinz** [comment]
请问能帮忙看看上面的问题吗，谢谢 @wzpan
