### ISSUE TITLE
安装脚本建议

### ISSUE THREAD

**Issue by zxszx4** [wzpan/wukong-starter#3]
潘老师，我在你视频另一个地址留言你没看到，我所在的省有点尴尬，尤其是上github有困难，所以很少来。在这里重新提个建议就是script/win.txt里第14行和linux.txt的第13行里RUN tar xvf swig-3.0.10.tar.gz应该是少了个参数z吧。
还有就是win.txt里面那个源不用加也可以运行，并且安装和运行成功，加了反而404错误，手动改源里的bionic为xenial才行。
因为才开始学，所以也不知道说的对不对，您参考下。

**Comment by wzpan** [comment]
好，我看下

**Comment by wzpan** [comment]
@zxszx4 谢谢指出，已修复！
