### ISSUE TITLE
在树莓派上安装的时候，install.sh里面有一个if...else...分支不能被执行到

### ISSUE THREAD

**Issue by lzhuo** [wzpan/wukong-starter#4]
![wukong_starter_issue](https://user-images.githubusercontent.com/7045839/60631382-d1aef100-9e31-11e9-89c8-4afc2419d456.jpg)

如截图所示，在树莓派上安装的时候，install.sh里面有一个if...else...分支不能被执行到

**Comment by wzpan** [comment]
wukong-starter 主要适用于普通 Linux 或者 Mac ，不建议在树莓派上使用。你可以看到我前面已经排除掉了树莓派：

![image](https://user-images.githubusercontent.com/1631405/60638254-3416ea00-9e50-11e9-9a90-6fa65edf3e60.png)

**Comment by lzhuo** [comment]
I see. 那完整版的wukong在树莓派上用有问题吗？

**Comment by wzpan** [comment]
完整版是没有问题的
